# Generated by Django 2.2.4 on 2020-04-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildMeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fitness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situps', models.IntegerField()),
                ('pushups', models.IntegerField()),
                ('plank_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usersfitness', models.ManyToManyField(related_name='fitness', to='buildMeapp.users')),
            ],
        ),
    ]
