# Generated by Django 2.2.4 on 2020-04-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildMeapp', '0002_fitness'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitness',
            name='squats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
