# Generated by Django 2.2.4 on 2020-04-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildMeapp', '0003_fitness_squats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness',
            name='plank_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='pushups',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='situps',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='squats',
            field=models.CharField(max_length=255),
        ),
    ]
