# Generated by Django 2.2.4 on 2020-04-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildMeapp', '0004_auto_20200425_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitness',
            name='usersfitness',
        ),
        migrations.AddField(
            model_name='fitness',
            name='userfitness',
            field=models.ManyToManyField(related_name='myfitness', to='buildMeapp.users'),
        ),
    ]
