# Generated by Django 2.2.4 on 2020-04-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildMeapp', '0005_auto_20200428_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear', models.CharField(max_length=255)),
                ('focus', models.CharField(max_length=255)),
                ('difficulty', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
