# Generated by Django 2.2.4 on 2020-04-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildMeapp', '0006_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
